title: My Wife's Betrayal
author: ThaDon
email: donavonmeade85@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta 
she's cheated on lil ole me for years 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ThaDon1105-github.com # DO NOT include the @ character, or else the build will fail!

show_excerpts: false# set to false to remove excerpts on the homepage
